<?php
$partner_id=0;
$service_url="https://www.kaltura.com";
// ADMIN secret:
$secret='';
// USER secret
$user_secret='';
$cdn_host='';
// the ID for the uiconf used for playing back the quiz entry. Used in play.php
// index.php uses KEA which automatically selects a player to edit with based on:
//'filter:objectType': 'KalturaUiConfFilter',
//'filter:tagsMultiLikeOr' : 'kea_'+KEA_VERSION,
//'service': 'uiConf',
//'action': 'listTemplates'
$playback_ui_conf_id=0;
?>

